name: 'KeepActionAlive'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # æ¯å‘¨æ—¥è§¦å‘

permissions:
  contents: write

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Empty Commit
        run: |
          git config --global user.email "marisa@marisa.ml"
          git config --global user.name "GuihongWang"
          git commit --allow-empty -m "ğŸ¤– Automated weekly activity ping"

      - name: Push changes
        run: git push https://x-access-token:${{ secrets.GH_TK }}@github.com/Marisa-Net/rdthimg-backend.git HEAD
